### PR TITLE
Back to dart:html

### PR DESCRIPTION
**Pull request by yjbanov**
This PR ditches package:js in favor or dart:html

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Found an issue while using this locally:

If there is no event associated with a setState call, then renderFrame never gets called.  potential modification is to remove the root event listener in the Tree and instead call this after setState somehow.

Ideally multiple calls to setState won't call `renderFrame` multiple times.  Something like this:

```dart
bool _isRendering = false;
void scheduleUpdate() {
  if (!_isRendering) {
    _isRendering = true;
    scheduleMicrotask(() {
     tree.renderFrame();
     _isRendering = false;
   });
  }
}

```

**Comment by yjbanov** [comment]
Good catch. Should it be a microtask or `requestAnimationFrame`?

**Comment by jonahwilliams** [comment]
`requestAnimationFrame` makes more sense to me since we can more easily batch an update across the entire app

**Comment by yjbanov** [comment]
Yes! Travis works again!

**Pull request merged**
