### PR TITLE
Example implementation of new widget concept (WIP)

### PR DESCRIPTION
**Pull request by jonahwilliams**
This is not a complete implementation - I mostly focused on the API and not making it efficient (everything is still backed by Element).

### CODE REVIEW

**Comment by yjbanov** [comment]
Wow, you've explored quite a bit here! I've been working in this direction too, and the good news is there isn't too much overlap with what I've been working on, which is a collection of abstract classes to help build building blocks such as event arenas and layouts. I'll upload a PR and let's sit down and talk about how we can reconcile these two.

**Comment by yjbanov** [comment]
Here it is: https://github.com/yjbanov/butterfly/pull/25

**Comment by yjbanov** [comment]
With #25 the new classes - Column, Row, Anchor - could be based on ElementBase/SingleChildElementBase, and EventArena on Decoration. But I'm also OK with starting with something and refactoring later. So, LGTM.

**Comment by yjbanov** [comment]
Has this been superseded by https://github.com/yjbanov/butterfly/pull/27? Should we close this?

**Comment by jonahwilliams** [comment]
Yeah let's close this, it will be easier to make the changes in smaller prs

**Pull request closed without merging**
